- name: Play Variables
  hosts: localhost
  connection: localhost
  vars:
    URL: play.google.com
  tasks:
    - name: Print URL
      ansible.buildin.debug:
        msg: "{{ URL }}"



#In Ansible we access variables with {{ }}
#Also, if the value is variable or starts with variables then we need to quote it ( Double Quotes Preferred)
#key: "{{ val }}"
#key: "{{ val }} some-other string"
#key: some - {{ val }}  # this does not require quotes.


- name: Task Variables
  hosts: localhost
  connection: localhost
  tasks:
    - name: Print URL
      ansible.buildin.debug:
        msg: "{{ URL }}"
      vars:
        URL: tasks.google.com

- name: Role Variables
  hosts: localhost
  connection: localhost
  roles:
    - demo